# **Assignment 4**

### **Web Scraping**
It is the process of extracting data from websites using programs instead of manually copying information. In Python, it is commonly done using libraries like Requests and BeautifulSoup, which help download and parse webpage content. It is useful for collecting data such as text, tables, and statistics from the internet.

In [ ]:
#Libraries used:
import requests
from bs4 import BeautifulSoup

In [ ]:
#Fetch webpage content and extract data without using headers.
url = "http://scrapethissite.com/pages/simple/"
response = requests.get(url)

print(response.status_code)

soup = BeautifulSoup(response.text, "html.parser")
print(soup)

200
<!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping</title>
<link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping." name="description"/>
<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
<link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
<meta content="noindex" name="robots"/>
<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet"/>
</head>
<body>
<nav id="site-nav">
<div class="container">
<div class="col-md-12">
<ul class="nav nav-tabs">
<li id="nav-homepage">
<a class="nav-link hidden-sm hidden-xs" href="/">
<img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                Scrape This Site
                            </a>
</li>
<li id="nav-sandbox">
<a class="nav-link" href="/pages/">
<i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
</li>
<li id="nav-lessons">
<a class="nav-link" href="/lessons/">
<i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
</li>
<li id="nav-faq">
<a class="nav-link" href="/faq/">
<i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
</li>
<li class="pull-right" id="nav-login">
<a class="nav-link" href="/login/">
                                Login
                            </a>
</li>
</ul>
</div>
</div>
</nav>
<script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>
<div id="page">
<section id="countries">
<div class="container">
<div class="row">
<div class="col-md-12">
<h1>
                            Countries of the World: A Simple Example
                            <small>250 items</small>
</h1>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-12">
<p class="lead">
                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.
                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country's name.
                        </p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-6">
<p>
<i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">4 video lessons</a> that show you how to scrape this page.
                        </p>
<hr/>
</div>
<div class="col-md-6 text-right">
<p>

                                Data via
                                <a class="data-attribution" href="http://peric.github.io/GetCountries/" target="_blank">http://peric.github.io/GetCountries/</a>
</p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br/>
<strong>Population:</strong> <span class="country-population">84000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ae"></i>
                            United Arab Emirates
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br/>
<strong>Population:</strong> <span class="country-population">4975593</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-af"></i>
                            Afghanistan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kabul</span><br/>
<strong>Population:</strong> <span class="country-population">29121286</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ag"></i>
                            Antigua and Barbuda
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">St. John's</span><br/>
<strong>Population:</strong> <span class="country-population">86754</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ai"></i>
                            Anguilla
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">The Valley</span><br/>
<strong>Population:</strong> <span class="country-population">13254</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-al"></i>
                            Albania
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Tirana</span><br/>
<strong>Population:</strong> <span class="country-population">2986952</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-am"></i>
                            Armenia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Yerevan</span><br/>
<strong>Population:</strong> <span class="country-population">2968000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ao"></i>
                            Angola
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Luanda</span><br/>
<strong>Population:</strong> <span class="country-population">13068161</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-aq"></i>
                            Antarctica
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">None</span><br/>
<strong>Population:</strong> <span class="country-population">0</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ar"></i>
                            Argentina
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br/>
<strong>Population:</strong> <span class="country-population">41343201</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-as"></i>
                            American Samoa
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br/>
<strong>Population:</strong> <span class="country-population">57881</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-at"></i>
                            Austria
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Vienna</span><br/>
<strong>Population:</strong> <span class="country-population">8205000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-au"></i>
                            Australia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Canberra</span><br/>
<strong>Population:</strong> <span class="country-population">21515754</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-aw"></i>
                            Aruba
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br/>
<strong>Population:</strong> <span class="country-population">71566</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ax"></i>
                            Åland
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br/>
<strong>Population:</strong> <span class="country-population">26711</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-az"></i>
                            Azerbaijan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Baku</span><br/>
<strong>Population:</strong> <span class="country-population">8303512</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ba"></i>
                            Bosnia and Herzegovina
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br/>
<strong>Population:</strong> <span class="country-population">4590000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bb"></i>
                            Barbados
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br/>
<strong>Population:</strong> <span class="country-population">285653</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bd"></i>
                            Bangladesh
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Dhaka</span><br/>
<strong>Population:</strong> <span class="country-population">156118464</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-be"></i>
                            Belgium
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Brussels</span><br/>
<strong>Population:</strong> <span class="country-population">10403000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bf"></i>
                            Burkina Faso
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br/>
<strong>Population:</strong> <span class="country-population">16241811</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">274200.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bg"></i>
                            Bulgaria
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sofia</span><br/>
<strong>Population:</strong> <span class="country-population">7148785</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">110910.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bh"></i>
                            Bahrain
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Manama</span><br/>
<strong>Population:</strong> <span class="country-population">738004</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">665.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bi"></i>
                            Burundi
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bujumbura</span><br/>
<strong>Population:</strong> <span class="country-population">9863117</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">27830.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bj"></i>
                            Benin
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Porto-Novo</span><br/>
<strong>Population:</strong> <span class="country-population">9056010</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">112620.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bl"></i>
                            Saint Barthélemy
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Gustavia</span><br/>
<strong>Population:</strong> <span class="country-population">8450</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">21.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bm"></i>
                            Bermuda
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Hamilton</span><br/>
<strong>Population:</strong> <span class="country-population">65365</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">53.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bn"></i>
                            Brunei
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bandar Seri Begawan</span><br/>
<strong>Population:</strong> <span class="country-population">395027</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">5770.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bo"></i>
                            Bolivia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sucre</span><br/>
<strong>Population:</strong> <span class="country-population">9947418</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1098580.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bq"></i>
                            Bonaire
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kralendijk</span><br/>
<strong>Population:</strong> <span class="country-population">18012</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">328.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-br"></i>
                            Brazil
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Brasília</span><br/>
<strong>Population:</strong> <span class="country-population">201103330</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">8511965.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bs"></i>
                            Bahamas
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Nassau</span><br/>
<strong>Population:</strong> <span class="country-population">301790</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">13940.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bt"></i>
                            Bhutan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Thimphu</span><br/>
<strong>Population:</strong> <span class="country-population">699847</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">47000.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bv"></i>
                            Bouvet Island

In [ ]:
#Using def, strip(), get_text(), text. Our objective is to create reusable scraping function and clean text.

import requests
from bs4 import BeautifulSoup

def scrape_quotes():
    url = "https://quotes.toscrape.com/"
    response = requests.get(url)
    soup = BeautifulSoup(response.text, "html.parser")

    quotes = soup.find_all('span', class_='text')
    authors = soup.find_all('small', class_='author')

    for quote, author in zip(quotes, authors):
        print(author.get_text(strip=True), "—",
              quote.get_text(strip=True))

scrape_quotes()

Albert Einstein — “The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”
J.K. Rowling — “It is our choices, Harry, that show what we truly are, far more than our abilities.”
Albert Einstein — “There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”
Jane Austen — “The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”
Marilyn Monroe — “Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”
Albert Einstein — “Try not to become a man of success. Rather become a man of value.”
André Gide — “It is better to be hated for what you are than to be loved for what you are not.”
Thomas A. Edison — “I have not failed. I've just found 10,000 ways that won't work.”
Eleanor Roosevelt — “A woman is like a tea bag; you never know how strong it is until it's in hot water.”
Steve Martin — “A day without sunshine is like, you know, night.”

In [ ]:
#Web Scraping With Header. The purpose of using Header is because some websites block bots. Headers make requests look like a browser.

import requests
from bs4 import BeautifulSoup

url = "https://quotes.toscrape.com/"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.text, "html.parser")

authors = soup.find_all('small', class_='author')

for a in authors[:5]:
    print(a.text)

Albert Einstein
J.K. Rowling
Albert Einstein
Jane Austen
Marilyn Monroe

In [ ]:
# Using enumerate() to add numbering while printing scraped data.
import requests
from bs4 import BeautifulSoup

url = "https://quotes.toscrape.com/"
response = requests.get(url)

soup = BeautifulSoup(response.text, "html.parser")

quotes = soup.find_all('span', class_='text')

for i, quote in enumerate(quotes[:5], 1):
    print(f"{i}. {quote.text}")

1. “The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”
2. “It is our choices, Harry, that show what we truly are, far more than our abilities.”
3. “There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”
4. “The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”
5. “Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”

In [ ]:
# Scrape an HTML table and perform operations using Pandas DataFrame.

# Step 1 : Importing Libraries
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [ ]:
# Step 2 : Scrape the table
url = "https://www.worldometers.info/world-population/population-by-country/"
response = requests.get(url)

soup = BeautifulSoup(response.text, "html.parser")

table = soup.find("table")
rows = table.find_all("tr")

In [ ]:
# Step 3: Extract Data
data = []

for row in rows[1:]:   # skip header
    cols = row.find_all("td")

    country = cols[1].get_text(strip=True)
    population = cols[2].get_text(strip=True)

    data.append([country, population])

In [ ]:
# Step 4: Create DataFrame
df = pd.DataFrame(data, columns=["Country", "Population"])

print(df.head())

         Country     Population
0          India  1,476,625,576
1          China  1,412,914,089
2  United States    349,035,494
3      Indonesia    287,886,782
4       Pakistan    259,299,791

In [ ]:
# Step 5 : Table (DataFrame) Operations
# -> Check datatypes
print(df.dtypes)
# -> Convert population to numeric
df["Population"] = df["Population"].str.replace(",", "").astype(float)
# Select columns
df["Country"]
df[["Country", "Population"]]

Country       object
Population    object
dtype: object

              Country    Population
0               India  1.476626e+09
1               China  1.412914e+09
2       United States  3.490355e+08
3           Indonesia  2.878868e+08
4            Pakistan  2.592998e+08
..                ...           ...
229        Montserrat  4.328000e+03
230  Falkland Islands  3.465000e+03
231           Tokelau  2.691000e+03
232              Niue  1.822000e+03
233          Holy See  5.060000e+02

[234 rows x 2 columns]

In [ ]:
# Filter data
df[df["Country"] == "India"]
# Sort values
df.sort_values(by="Population", ascending=False)

              Country    Population
0               India  1.476626e+09
1               China  1.412914e+09
2       United States  3.490355e+08
3           Indonesia  2.878868e+08
4            Pakistan  2.592998e+08
..                ...           ...
229        Montserrat  4.328000e+03
230  Falkland Islands  3.465000e+03
231           Tokelau  2.691000e+03
232              Niue  1.822000e+03
233          Holy See  5.060000e+02

[234 rows x 2 columns]

In [ ]:
# Save file
df.to_csv("population.csv", index=False)

In [ ]:
# Step 6 : Basic analysis
print(df.describe())

         Population
count  2.340000e+02
mean   3.546514e+07
std    1.394742e+08
min    5.060000e+02
25%    4.389268e+05
50%    5.776466e+06
75%    2.428835e+07
max    1.476626e+09

In [ ]:
# Step 7 : Loop through table
for index, row in df.iterrows():
    print(row['Country'], "-", row['Population'])

India - 1476625576.0
China - 1412914089.0
United States - 349035494.0
Indonesia - 287886782.0
Pakistan - 259299791.0
Nigeria - 242431832.0
Brazil - 213562666.0
Bangladesh - 177818044.0
Russia - 143394458.0
Ethiopia - 138902185.0
Mexico - 132997658.0
Japan - 122427731.0
Egypt - 120101175.0
Philippines - 117724471.0
DR Congo - 116452162.0
Vietnam - 102177431.0
Iran - 93168497.0
Turkey - 87926082.0
Germany - 83644258.0
Tanzania - 72563780.0
Thailand - 71559614.0
United Kingdom - 69931528.0
France - 66746401.0
South Africa - 65453084.0
Italy - 58926166.0
Kenya - 58636412.0
Myanmar - 55184819.0
Colombia - 53936226.0
Sudan - 53282719.0
Uganda - 52761469.0
South Korea - 51600388.0
Algeria - 48028334.0
Iraq - 48007437.0
Spain - 47850793.0
Argentina - 46003734.0
Afghanistan - 45047069.0
Yemen - 42961653.0
Canada - 40467728.0
Angola - 40215179.0
Ukraine - 39535849.0
Morocco - 38762441.0
Poland - 37843188.0
Uzbekistan - 37724223.0
Mozambique - 36639851.0
Malaysia - 36385115.0
Ghana - 35697557.0
Saudi Arabia - 35165787.0
Peru - 34922148.0
Madagascar - 33522052.0
CÃ´te d'Ivoire - 33494346.0
Cameroon - 30640817.0
Nepal - 29629410.0
Niger - 28814878.0
Venezuela - 28633711.0
Australia - 27227096.0
North Korea - 26633691.0
Syria - 26472497.0
Mali - 25932275.0
Burkina Faso - 24601700.0
Sri Lanka - 23348315.0
Taiwan - 23011292.0
Malawi - 22785535.0
Zambia - 22521915.0
Chad - 21560380.0
Kazakhstan - 21083626.0
Somalia - 20305907.0
Chile - 19945850.0
Senegal - 19366548.0
Guatemala - 18967978.0
Romania - 18800605.0
Netherlands - 18448775.0
Ecuador - 18444506.0
Cambodia - 18051219.0
Zimbabwe - 17273580.0
Guinea - 15441993.0
Benin - 15170419.0
Rwanda - 14889693.0
Burundi - 14729157.0
Bolivia - 12749291.0
South Sudan - 12436037.0
Tunisia - 12415138.0
Haiti - 12037506.0
Belgium - 11774642.0
Dominican Republic - 11609500.0
Jordan - 11589532.0
United Arab Emirates - 11574682.0
Honduras - 11184760.0
Tajikistan - 10978599.0
Papua New Guinea - 10947848.0
Cuba - 10892659.0
Sweden - 10701047.0
Czech Republic (Czechia) - 10527781.0
Azerbaijan - 10454855.0
Portugal - 10395362.0
Togo - 9930918.0
Greece - 9897115.0
Israel - 9647689.0
Hungary - 9585818.0
Austria - 9107266.0
Switzerland - 9007798.0
Sierra Leone - 8996745.0
Belarus - 8937018.0
Laos - 7974017.0
Turkmenistan - 7736632.0
Libya - 7539851.0
Kyrgyzstan - 7400465.0
Hong Kong - 7378602.0
Nicaragua - 7097329.0
Paraguay - 7095279.0
Bulgaria - 6667659.0
Serbia - 6641964.0
Congo - 6637785.0
El Salvador - 6391253.0
Denmark - 6023520.0
Singapore - 5905748.0
Lebanon - 5897467.0
Liberia - 5853949.0
Central African Republic - 5698984.0
State of Palestine - 5692790.0
Oman - 5671458.0
Norway - 5652989.0
Finland - 5621739.0
Mauritania - 5461319.0
Slovakia - 5451342.0
Ireland - 5356950.0
New Zealand - 5287479.0
Costa Rica - 5174789.0
Kuwait - 5102773.0
Panama - 4625718.0
Croatia - 3822345.0
Georgia - 3804642.0
Eritrea - 3682669.0
Mongolia - 3556798.0
Uruguay - 3382537.0
Puerto Rico - 3222688.0
Qatar - 3173559.0
Namibia - 3153246.0
Bosnia and Herzegovina - 3114242.0
Moldova - 2961253.0
Armenia - 2930915.0
Gambia - 2884079.0
Jamaica - 2833403.0
Lithuania - 2797338.0
Albania - 2751025.0
Gabon - 2647399.0
Botswana - 2603388.0
Lesotho - 2389336.0
Guinea-Bissau - 2297808.0
Slovenia - 2114573.0
Equatorial Guinea - 1984468.0
Latvia - 1835935.0
North Macedonia - 1804063.0
Bahrain - 1675572.0
Trinidad and Tobago - 1513268.0
Timor-Leste - 1436923.0
Cyprus - 1382334.0
Estonia - 1331062.0
Eswatini - 1269859.0
Mauritius - 1265059.0
Djibouti - 1199459.0
Fiji - 937282.0
Comoros - 899010.0
RÃ©union - 886298.0
Solomon Islands - 858288.0
Guyana - 840890.0
Bhutan - 802214.0
Macao - 723188.0
Luxembourg - 687448.0
Suriname - 645256.0
Montenegro - 626233.0
Western Sahara - 610813.0
Malta - 549011.0
Maldives - 531517.0
Cabo Verde - 529630.0
Brunei - 469775.0
Belize - 428644.0
Bahamas - 404628.0
Iceland - 402329.0
Guadeloupe - 372453.0
Mayotte - 347536.0
Vanuatu - 342564.0
Martinique - 337711.0
French Guiana - 318872.0
New Caledonia - 297892.0
French Polynesia - 283076.0
Barbados - 282724.0
Sao Tome & Principe - 244994.0
Samoa - 220528.0
CuraÃ§ao - 185440.0
Saint Lucia - 180488.0
Guam - 170185.0
Kiribati - 138445.0
Seychelles - 134959.0
Grenada - 117362.0
Micronesia - 114183.0
Aruba - 108164.0
Tonga - 103291.0
St. Vincent & Grenadines - 99245.0
Antigua and Barbuda - 94626.0
Isle of Man - 84055.0
Andorra - 83753.0
U.S. Virgin Islands - 83400.0
Cayman Islands - 77196.0
Dominica - 65511.0
Bermuda - 64459.0
Faeroe Islands - 56526.0
Greenland - 55629.0
Turks and Caicos - 47148.0
Saint Kitts & Nevis - 46992.0
American Samoa - 45319.0
Sint Maarten - 44447.0
Northern Mariana Islands - 42914.0
Gibraltar - 40867.0
Liechtenstein - 40368.0
British Virgin Islands - 39936.0
Monaco - 38087.0
Marshall Islands - 35075.0
San Marino - 33605.0
Caribbean Netherlands - 31913.0
Saint Martin - 23898.0
Palau - 17614.0
Anguilla - 14817.0
Cook Islands - 12826.0
Nauru - 12101.0
Saint Barthelemy - 11550.0
Wallis & Futuna - 11113.0
Tuvalu - 9362.0
Saint Pierre & Miquelon - 5513.0
Saint Helena - 5147.0
Montserrat - 4328.0
Falkland Islands - 3465.0
Tokelau - 2691.0
Niue - 1822.0
Holy See - 506.0